name: artifact-share-data-between-jobs
on:
  push:
    branches: context

jobs:
  show:
    name: show
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
           echo ${{ github }}
           echo ${{ github.run_id }}
           echo ${{ github.run_number}}
           PACKAGE_VERSION=v1.2.${{ github.run_id }}
           echo $PACKAGE_VERSION

  
 