name: using docker-compose
on:
  push:
    branches: [ docker-compose ]

jobs:
  using-docker-compose:
    name: set-up-docker
    runs-on: ubuntu-18.04
    steps:
      - name: Start Mongo and Redis
        run: |
          cat <<EOF > docker-compose.yml
            services:

              redis:
                image: redis:5.0.7-alpine
                container_name: redis-5.0.7
                command: [ "redis-server", "--appendonly", "yes" ]
                volumes:
                  - ~/data/redis-data:/data
                restart: always
                network_mode: host

              mongo:
                image: mongo
                volumes:
                  - ./mongo/db:/data/db
                # ports:
                #     - 27017:27017
                restart: always
                network_mode: host
          EOF
          docker-compose -f "docker-compose.yml" up -d --build
          docker ps
          lsof -i:27017
          lsof -i:6379


